### ISSUE TITLE
featureCounts parameters

### ISSUE THREAD

**Issue by mevers** [vivekbhr/Subread_to_DEXSeq#1]
Hi Vivek.

Thanks for providing the Subread_to_DEXSeq scripts.

I believe there are two typos in the featureCounts example you give
`/path/to/subread-1.4.6-p2/bin/featureCounts -f -O -s 2 -p -T 40 -F GTF -a dm6_ens76_flat.gtf -o dm6_fCount.out Cont_1.bam Cont_2.bam Test_1.bam Test_2.bam`
1. You use `-s 2` but this would count reads if they are located on the opposite strand of the annotated feature. Are you sure this is correct?
2. Additionally, if I use your `dexseq_prepare_annotation2.py` to prepare the flattened GTF file, I need to add `-t exonic_part` to the featureCounts arguments to perform counting at the exon level.

Cheers,
Maurits

**Comment by vivekbhr** [comment]
Hi Maurits

Thanks for your input. The option `-s 2` should be fine with featurecounts for most of the stranded illumina RNA-Seq experiments, which corresponds to tophat's `fr-firststrand`. But I indeed forgot to add the `-t` option in the example. I have edited it now..

Best,
Vivek

**Comment by mevers** [comment]
Hi Vivek.

No worries & thanks for the update. So if I remember correctly `-s 2` in featureCounts corresponds to `-s reverse` in htseq-count? It might be worth making a note in your nice guide to help readers match parameters between different tools.

Best,
Maurits

**Comment by vivekbhr** [comment]
yes that's right. It's same as htseq-count `reverse` .. :+1:
