### ISSUE TITLE
GTF to GFF transformation

### ISSUE THREAD

**Issue by jingjiai** [vivekbhr/Subread_to_DEXSeq#12]
I downloaded the  Homo_sapiens.GRCh38.102.gtf from Ensembl,  but I am getting this error for the GTF to GFF transformation.

python /opt/anaconda3/lib/R/library/DEXSeq/python_scripts/dexseq_prepare_annotation.py  Homo_sapiens.GRCh38.102.gtf  dexseq.gff

 File "/opt/anaconda3/lib/R/library/DEXSeq/python_scripts/dexseq_prepare_annotation.py", line 129
    raise ValueError, "Same name found on two chromosomes: %s, %s" % ( str(l[i]), str(l[i+1]) )

^
SyntaxError: invalid syntax

so how can I to fix it?
thank you!

**Comment by vivekbhr** [comment]
I think its related to the python version. Could you tell me your python version?

**Comment by jingjiai** [comment]
My python version is 3.6.8

**Comment by vivekbhr** [comment]
Yes, the original script was in python2 (which is what you seem to have used and got the error). We have updated the script for python3 in this repository. Could you try it from our repo here?

**Comment by jingjiai** [comment]
You mean I should download it from github? 
I downloaded DEXSeq-1.28.0 from bioconductor before. It was in python2 , right?
But my R version is 3, is it suitable for your script?

**Comment by vivekbhr** [comment]
That's correct. the github version should be compatible to your python. And yes, the R version is not an issue.

**Comment by jingjiai** [comment]
OK, I will try it! Thanks!!!
