### ISSUE TITLE
problem for DEXseq

### ISSUE THREAD

**Issue by wilburnguo** [vivekbhr/Subread_to_DEXSeq#14]

**Comment by Polyalineli** [comment]
For me changing  255 to **254** in substr(aggregates$gene_id,1,255) line of DEXSeqDataSetFromFeatureCounts() solved the issue. Because in my case featurecounts cropped aggregate geneIDs of massively overlapped exons to 254 characters.

**Comment by LorenzoLF** [comment]
Same problem for me. Unfortunately changing 255 to 254 in substr(aggregates$gene_id,1,255) does not seem to fix it either. Has somebody found another fix? Thank you.

**Comment by HJosephLee** [comment]
In my case, there was an aggregated gene ID that was strangely long.  I removed it from both dcounts and aggregates, then everything worked.

**Comment by wilburnguo** [comment]
> m
