### ISSUE TITLE
long names of gene sets in the flattened gtf stop the R script

### ISSUE THREAD

**Issue by michalogit** [vivekbhr/Subread_to_DEXSeq#4]
Hey Vivek, 
Thanks for publishing this nice hack for combining the two useful genomic tools! 

I have tried it with hg38 from Encembl v86. The flattened annotation file happens to have one set having the complete name 351 chars long - it is PCDHG "cascade of genes". This gets truncated to 256 chars by featureCounts and causes your script to stop due not matching names. 

I have deleted this set from the gtf together with its 99 exons (as likely misleading for splicing anyway) and did the counting with such gtf, then everything worked OK. But perhaps there can be more polite solution your own way, such as truncating all names(exoninfo) to 256 characters etc....

Cheers, 
Michal

**Comment by vivekbhr** [comment]
Hey Michal

Thanks for the suggestion. Indeed, if I truncate the geneIDs it resolves the issue. I fixed it, and added a warning message in case truncating makes some geneIDs redundant (Although this didn't happen in my GRCh38 test, so it should be fine..)

Best,
Vivek

**Comment by michalogit** [comment]
Cool, thank you Vivek, will give it a try!  :)
