### ISSUE TITLE
"-t" argument, exonic_part

### ISSUE THREAD

**Issue by ccshao** [vivekbhr/Subread_to_DEXSeq#5]
Though I saw a closed issue said the `exonic_part` should be added, I found the **dexseq_prepare_annotation2.py** does NOT work with that argument.  There is no  `exonic_part` 
in the **dm6_ens76_flat.gtf** at all, it only appears in the **dm6_ens76_flat.gff**

Am I right that the "-t" parameter should be deleted?

**Comment by ccshao** [comment]
UPDATES: I removed the "-t" parameter. With the obtained exon counts I ran DEXSeq and compared to results by HTseq count approach. over 85% exons found in both analysis, and the fold change were extemely similar for these exons.

**Comment by vivekbhr** [comment]
@ccshao You're right the -t parameter is not needed.. I need to update the documentation

**Comment by vivekbhr** [comment]
Done
