### ISSUE TITLE
geneID/featureID truncated

### ISSUE THREAD

**Issue by ccshao** [vivekbhr/Subread_to_DEXSeq#6]
I saw a warning that one geneID got truncated, and in the R codes it said this is needed to match 
featureCounts. Could this truncate step be skipped now?

**Comment by vivekbhr** [comment]
actually if you run featurecounts, it truncates the geneIDs to 256 chars. So I also truncate that entry in our input GTF to match the featurecount output.. You'll get error if this step is skipped..

**Comment by ccshao** [comment]
Thanks. I manually added the truncated id back.
