### ISSUE TITLE
Error in DEXSeqDataSetFromFeatureCounts

### ISSUE THREAD

**Issue by sneha100895** [vivekbhr/Subread_to_DEXSeq#9]
Hi,

I'm trying to use your code to run DEXSeq using featureCounts output, but when I run 

dxd.fc <- DEXSeqDataSetFromFeatureCounts("counts_fCount.out", flattenedfile = "featurecountsgtf",sampleData = samp)

I get the following error message:

Error in DESeqDataSet(rse, design, ignoreRank = TRUE) : 
  some values in assay are not integers
In addition: Warning message:
 Error in DESeqDataSet(rse, design, ignoreRank = TRUE) : 
  some values in assay are not integers 

Could you please help me out with this as I'm not sure what the problem is.

Thanks,
Sneha

**Comment by vivekbhr** [comment]
Hi Sneha

Can you send me the first ~10 lines from your featurecounts output? It looks like one of the counts column doesn't have numbers, maybe it has characters.

**Comment by sneha100895** [comment]
Hi Vivek,

Please find attached an excel file with the first few lines of feature
counts output.

**Comment by vivekbhr** [comment]
I don't see an attachment

**Comment by sneha100895** [comment]
Hi, sorry for the late reply.

This is the link to the first few lines of feature counts output. 

https://studentuml-my.sharepoint.com/:x:/g/personal/sneha_suresh_student_uml_edu/EZmDjYu_uulNtTBRiwWx1i0B6Um5Wly9hve5_nA8W7ppSQ?e=KrlU5Z


All the counts columns are numeric, so I'm not sure why I'm getting an error.

**Comment by vivekbhr** [comment]
I see the problem. You are using some sort of normalized values.. the DEXSeq setting needs integers, not floats. You should use the raw counts obtained from featurecounts output (check the readme).
